# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run FFXIV Notification

on:
  workflow_dispatch:
  schedule:
    - cron: '05 0 * * 6'  # 00:05 UTC every Friday (7:05pm EDT)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run python
      env:
        USER_ID: ${{ secrets.USER_ID }}
        LODESTONE_URL: ${{ secrets.LODESTONE_URL }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        FFXIV_CHANNEL_ID: ${{ secrets.FFXIV_CHANNEL_ID }}
      run: |
        python main.py --ffxiv
